services:
  - type: web
    name: store-items
    env: node
    region: oregon
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: store-items-db
          property: connectionString

databases:
  - name: store-items-db
    databaseName: store_items
    user: store_user
    plan: free

